# These are supported funding model platforms

# github: # your-github-username
# patreon: # your-patreon-username
# ko_fi: # your-ko-fi-username
# custom: # your-custom-url

# Uncomment and add your funding info if you want to accept donations

