# Lexicon for ASR prompting (preserve diacritics; keep concise)

supermarkets:
  - "ALDI"
  - "Albert Heijn"
  - "Coop"
  - "Dirk"
  - "Gall en Gall"
  - "HEMA"
  - "Hoogvliet"
  - "Jumbo"
  - "LIDL"
  - "Makro"
  - "Plus"
  - "Spar"
  - "Vomar"

brands:
  - "Antinori"
  - "Banrock Station"
  - "Barefoot"
  - "Blossom Hill"
  - "Campo Alto"
  - "Campo Viejo"
  - "Casillero del Diablo"
  - "Chablis"
  - "Château"
  - "Cote du Rhone"
  - "Coterone"
  - "Côtes du Rhône"
  - "Côte du Ventoux"
  - "Cavicchioli"
  - "Errazuriz"
  - "Faustino"
  - "Frescobaldi"
  - "Gallo"
  - "Hardys"
  - "Jacob's Creek"
  - "JP Chenet"
  - "KWV"
  - "KWV Classic Collection"
  - "Les Jamelles"
  - "Lindeman's"
  - "Louis Jadot"
  - "Marqués de Riscal"
  - "Masi"
  - "Montes"
  - "Mouton Cadet"
  - "Nederburg"
  - "Penfolds"
  - "Robert Mondavi"
  - "Rustenberg"
  - "Santa Rita"
  - "Torres"
  - "Vinho Verde"
  - "Wolf Blass"
  - "Yellow Tail"
  - "Zonin"

grapes:
  - "aglianico"
  - "albariño"
  - "arneis"
  - "barbera"
  - "cabernet franc"
  - "cabernet sauvignon"
  - "carménère"
  - "chardonnay"
  - "chenin blanc"
  - "cinsault"
  - "clairette"
  - "garganega"
  - "garnacha"
  - "gewürztraminer"
  - "gruner veltliner"
  - "malbec"
  - "merlot"
  - "montepulciano"
  - "moscato"
  - "mourvèdre"
  - "muscat"
  - "nebbiolo"
  - "petite sirah"
  - "picpoul"
  - "pinot blanc"
  - "pinot grigio"
  - "pinot noir"
  - "primitivo"
  - "riesling"
  - "sangiovese"
  - "sauvignon"
  - "sauvignon blanc"
  - "semillon"
  - "shiraz"
  - "syrah"
  - "sylvaner"
  - "tannat"
  - "tempranillo"
  - "touriga nacional"
  - "torrontés"
  - "trebbiano"
  - "vermentino"
  - "verdejo"
  - "viognier"
  - "zweigelt"

regions:
  - "abruzzo"
  - "alentejo"
  - "alsace"
  - "barolo"
  - "barossa valley"
  - "beaujolais"
  - "bordeaux"
  - "bourgogne"
  - "cahors"
  - "casablanca valley"
  - "central otago"
  - "chianti"
  - "chablis"
  - "columbia valley"
  - "côtes du rhône"
  - "douro"
  - "friuli"
  - "hunter valley"
  - "jumilla"
  - "languedoc"
  - "loire"
  - "maipo"
  - "marlborough"
  - "mclaren vale"
  - "mendoza"
  - "mosel"
  - "napa valley"
  - "okanagan"
  - "piemonte"
  - "priorat"
  - "provence"
  - "puglia"
  - "ribera del duero"
  - "rheingau"
  - "rhone"
  - "rias baixas"
  - "rioja"
  - "sancerre"
  - "sicilië"
  - "sonoma"
  - "stellenbosch"
  - "toscane"
  - "trentino"
  - "valpolicella"
  - "veneto"
  - "wachau"

wine_terms:
  - "aanrader"
  - "absolute topper"
  - "afdronk"
  - "aroma"
  - "bio"
  - "biologisch"
  - "blend"
  - "body"
  - "borrelwijn"
  - "bubbels"
  - "cava"
  - "champagne"
  - "complex"
  - "crémant"
  - "cuvée"
  - "droog"
  - "evenwichtig"
  - "fruitig"
  - "geurprofiel"
  - "gran reserva"
  - "houtgelagerd"
  - "huiswijn"
  - "minerale tonen"
  - "mousserende"
  - "natuurwijn"
  - "organisch"
  - "parel"
  - "prijs kwaliteit"
  - "reserve"
  - "rood"
  - "rode"
  - "rosé"
  - "rond"
  - "single vineyard"
  - "tannine"
  - "vegan wijn"
  - "verborgen parel"
  - "vin blanc"
  - "vino blanco"
  - "vino rosso"
  - "vinho"
  - "vinho tinto"
  - "vol"
  - "wit"
  - "wijn"
  - "wijntest"
  - "wijntje"
  - "wijnen"
  - "witte"
  - "zoet"
