# Docker Compose for Vinly Wine Discovery Platform
# Local development environment

version: '3.8'

services:
  # ============================================
  # MongoDB Database
  # ============================================
  mongodb:
    image: mongo:7
    container_name: vinly-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: vinly-local-dev
      MONGO_INITDB_DATABASE: vinly
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - vinly-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # ============================================
  # Backend API (FastAPI)
  # ============================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: vinly-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # MongoDB connection (local container)
      MONGODB_URI: mongodb://admin:vinly-local-dev@mongodb:27017/vinly?authSource=admin
      # OpenAI API key (set in .env file)
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # CORS origins (include localhost without port for browser default)
      CORS_ORIGINS: http://localhost,http://localhost:3000,http://localhost:5173,http://localhost:80,http://frontend:80
      # Environment
      ENVIRONMENT: development
      LOG_LEVEL: INFO
    volumes:
      # Mount code for hot reload (development)
      - ./backend/app:/app/app:ro
      - ./backend/config:/app/config:ro
      - ./backend/scripts:/app/scripts:ro
      # Persistent storage for videos, frames, and wine images
      - backend_static:/app/static
      - backend_temp_videos:/app/temp/videos
      - backend_temp_frames:/app/temp/frames
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - vinly-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================
  # Frontend (React + Vite + nginx)
  # ============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: vinly-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - vinly-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  # ============================================
  # Mongo Express (Optional - Database UI)
  # ============================================
  mongo-express:
    image: mongo-express:latest
    container_name: vinly-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: vinly-local-dev
      ME_CONFIG_MONGODB_URL: mongodb://admin:vinly-local-dev@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - vinly-network
    profiles:
      - tools  # Only start with: docker-compose --profile tools up

# ============================================
# Networks
# ============================================
networks:
  vinly-network:
    driver: bridge

# ============================================
# Volumes (Persistent Data)
# ============================================
volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  backend_static:
    driver: local
  backend_temp_videos:
    driver: local
  backend_temp_frames:
    driver: local

