# Render Blueprint - Deploy Vinly with Docker
# Optimized Docker deployment with all dependencies included
# Learn more: https://render.com/docs/blueprint-spec

services:
  # Backend API - FastAPI with Docker
  - type: web
    name: vinly-backend
    runtime: docker
    region: frankfurt  # Closest to Netherlands
    plan: starter  # $7/month - recommended for production (use 'free' for testing)
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy on git push
    autoDeploy: true
    
    # Disk storage for wine images, videos, frames
    disk:
      name: vinly-storage
      mountPath: /app/static
      sizeGB: 1
    
    # Environment variables (set these in Render dashboard)
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Manual - get from platform.openai.com
      
      - key: MONGODB_URI
        sync: false  # Manual - get from MongoDB Atlas
      
      - key: CORS_ORIGINS
        value: https://vinly-backend.onrender.com  # Update with your actual domain if needed
      
      - key: ENVIRONMENT
        value: production
      
      - key: LOG_LEVEL
        value: INFO

# Notes:
# ============================================
# Docker Deployment Benefits:
# ============================================
# ✅ All dependencies included (FFmpeg, Chromium, yt-dlp)
# ✅ Consistent builds - no more dependency issues
# ✅ Faster builds with layer caching
# ✅ Portable - works on any platform
# ✅ Secure - runs as non-root user
#
# ============================================
# Setup Instructions:
# ============================================
# 1. Create MongoDB Atlas cluster (free M0 tier):
#    https://www.mongodb.com/cloud/atlas/register
#
# 2. Get connection string:
#    mongodb+srv://username:password@cluster.mongodb.net/vinly
#
# 3. Get OpenAI API key:
#    https://platform.openai.com/api-keys
#
# 4. Deploy to Render:
#    - Connect your GitHub repo
#    - Render auto-detects this blueprint
#    - Set OPENAI_API_KEY and MONGODB_URI in dashboard
#    - Deploy!
#
# ============================================
# Plan Options:
# ============================================
# - Free tier: Backend sleeps after 15min (50s cold start)
#   Change 'plan: starter' to 'plan: free'
#
# - Starter ($7/month): Always-on, no cold starts
#   Recommended for production use
#
# ============================================
# Deployment:
# ============================================
# Backend: https://vinly-backend.onrender.com
# API Docs: https://vinly-backend.onrender.com/docs
# Health: https://vinly-backend.onrender.com/health
